### ISSUE TITLE
lxd doesn't start VMs with qemu >= 5.2.0

### ISSUE THREAD

**Issue by subpop** [ganto/copr-lxc4#13]
There's an upstream issue[1] with `lxd` and qemu >= 5.2.0 that just started affecting Fedora 34 since it ships qemu 5.2.0. It's fixed upstream[2], but not in a release yet.

1: https://github.com/lxc/lxd/issues/8416
2: https://github.com/lxc/lxd/pull/8700

**Comment by subpop** [comment]
I was able to pull the patch from upstream and build it into lxd with the attached format-patch. I'll get a forked repository and PR opened up later.

[0001-Automatic-commit-of-package-lxd-release-4.12-0.2.zip](https://github.com/ganto/copr-lxc4/files/6387019/0001-Automatic-commit-of-package-lxd-release-4.12-0.2.zip)

**Comment by ganto** [comment]
Thanks a lot for the PR. Give me another day to release a new package.

**Comment by ganto** [comment]
I slightly adjusted the `Suggestion` lines to also include the necessary package for Fedora 33 and triggered a new release. Should be available in the next half an hour. Thanks a lot for your contribution. I hope the COPR package now also works for you.

**Comment by ganto** [comment]
As far as my testing goes, the package seems to work fine on Fedora 34. I also updated the [wiki](https://github.com/ganto/copr-lxc4/wiki#virtual-machine-support) to point out the new packages required for virtual machine support.

I'm closing the issue. Please re-open if you still have issues with that.
