### ISSUE TITLE
fedora34 post kernel 5.12.8-300 unable to enter running container

### ISSUE THREAD

**Issue by davehatton** [ganto/copr-lxc4#16]
following a kernel upgrade post  5.12.8-300 I am unable to enter a running container with lxc shell or exec

there are some selinux errors but I don;t see an avc in audit logs that might fix this.

```
lxc secure-falcon 20210615165538.480 ERROR    selinux - lsm/selinux.c:selinux_process_label_set_at:158 - Operation not permitted - Failed to set AppArmor SELinux label to "system_u:system_r:spc_t:s0"
lxc secure-falcon 20210615165538.480 ERROR    attach - attach.c:do_attach:1336 - Failed to attach to container
```

this is using your latest build from copr

**Comment by davehatton** [comment]
tut ... today after opening this and searching I find the likely cause:
https://github.com/lxc/lxc/issues/3863
and a fix going into the kernel
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=591a22c14d3f45cc38bd1931c593c221df2f1881

**Comment by davehatton** [comment]
sorry for the noise with this ... upgrading to  rawhide 5.13.0.0.rc6 .45 kernel fixes the issue.

**Comment by ganto** [comment]
Thanks for this information. Actually I was a bit lazy rebooting my laptop, so I didn't notice so far.
