### ISSUE TITLE
missing dependency: attr (provides setfattr)

### ISSUE THREAD

**Issue by Ostheer** [ganto/copr-lxc4#19]
Problems concerns LXD on a fresh install of Fedora 35 Server Edition.

Installation finishes succesfully, but systemd service fails to start with the following message:

```
Error: exec: "setfattr": executable file not found in $PATH
```

Manually installing the `attr` package with dnf solves the issue.

**Comment by ganto** [comment]
Thanks for reporting. I'll add this dependency with the next lxd package update.
