### ISSUE TITLE
Multi-user support

### ISSUE THREAD

**Issue by b11p** [ganto/copr-lxc4#21]
LXD supports multi-user setup starting from 4.22:

https://discourse.ubuntu.com/t/easy-multi-user-lxd-setup/26215

However, all documentation about the multi-user setup uses snap to config.

Does your package support multi-user installation? How do I enable it?

**Comment by ganto** [comment]
Hmn, the magic seems happen in this command `snap set lxd daemon.user.group=users`. No idea what this is doing, but I'll go dig into the source code to figure out how this is working to give you an answer. Please give me a few days.

**Comment by ganto** [comment]
From what I found so far this needs an additional binary `lxd-user` that is not built by the default `Makefile`. It also needs an additional systemd socket and service that would be used as a proxy by client requests from lower privileged users. My package definitely doesn't support such a setup yet.

I'll try to reverse engineer it to work on Fedora but can't promise any timeline.

**Comment by ganto** [comment]
Multi-user setup is available in the Incus RPM via user group `incus`.

For LXD it's complicated to add as I'm not using the default location for the daemon socket and the client seems not to find the user socket when I tried. Need to invest some more time into it.

**Comment by ganto** [comment]
I was having a look at `lxd-user` support again as I took some time to clean up the `lxd.spec` file. Unfortunately [upstream implemented it](https://discourse.ubuntu.com/t/easy-multi-user-lxd-setup/26215/17) via a snap-specific [lxc](https://github.com/canonical/lxd-pkg-snap/blob/latest-edge/snapcraft/commands/lxc) wrapper script which is awkward to replicate in a RPM installation.

I then made another attempt by adding a second socket `/var/lib/lxd/user.socket` and adjusting `$LXD_SOCKET`. The socket was owned by a group 'lxd-users' where I was a member of. The log shows that something was done:
```
Dec 29 10:23:30 fedora38.example.com lxd-user[3003]: time="2023-12-29T10:23:30Z" level=info msg="Starting up the server"
Dec 29 10:23:30 fedora38.example.com lxd-user[3003]: time="2023-12-29T10:23:30Z" level=info msg="Setting up LXD for uid 1000"
```
```
# lxc project list | grep user-1000
| user-1000         | YES    | YES      | YES             | YES             | NO       | YES           | User restricted project for "vagrant" (1000) | 1       |
```
However, when querying LXD with a user it displays the wrong project:
```
$ LXD_SOCKET=/var/lib/lxd/user.socket lxc info | grep 'project:'
  project: default
```
And every other command would fail with an authentication error:
```
$ LXD_SOCKET=/var/lib/lxd/user.socket lxc list
Error: not authorized
```

As this doesn't seem to be an official feature for LXD but "simply works" for Incus I'm going to give up. Please use Incus if you need this functionality.
