### ISSUE TITLE
incus

### ISSUE THREAD

**Issue by dejlek** [ganto/copr-lxc4#22]
Do you by any chance plan to include incus in this repo? https://github.com/lxc/incus

**Comment by ganto** [comment]
Sure, as soon as there is a stable release I will add Incus. And then it will also be a good occasion to try and bring it to Fedora upstream.

**Comment by ganto** [comment]
Incus is now available as an initial RPM. Please try it and report some issues. You might also want to have a look at the updated [installation instructions](https://github.com/ganto/copr-lxc4/wiki#incus) as there were some slight changes necessary compared with the LXD package.
