### ISSUE TITLE
LXD UI

### ISSUE THREAD

**Issue by almereyda** [ganto/copr-lxc4#29]
The LXD Snap brings an LXD UI since `v5.14`:

* [How to access the LXD web UI - Canonical LXD documentation](https://documentation.ubuntu.com/lxd/en/latest/howto/access_ui/)
* [canonical/lxd-ui: Easy and accessible container and virtual machine management. A browser interface for LXD](https://github.com/canonical/lxd-ui)

Is there a chance this could be included in these LXD builds here?

As per the definition of the snap, this only seems to copy some static files into an expected location, and is then available?

https://github.com/canonical/lxd-pkg-snap/blob/1b5997236d12a73a402a711e1dd3d9274eb43045/snapcraft.yaml#L1523-L1544

`ui.enabled=true` then exports an environment variable with the location of the UI:

https://github.com/canonical/lxd-pkg-snap/blob/1b5997236d12a73a402a711e1dd3d9274eb43045/snapcraft/commands/daemon.start#L449-L453

LXD activates the UI, if this variable is present and set:

https://github.com/canonical/lxd/blob/1be6a0bc5e65a157d32afbac4b24ee3b0d8fc791/lxd/api.go#L70-L71

Would it be possible to replicate these steps with the COPR and RPM build infrastructure?

Else I've seen plans in Incus land to repackage it, which could be used as a reference point.

**Comment by ganto** [comment]
Thanks for the hint. I'll have a look at it.

**Comment by ganto** [comment]
I was able to build a first version of the `lxd-ui` RPM. Unfortunately it was only successful for x86_64. 

You can give it a try by installing the package `dnf install lxd-ui` and manually adding the `LXD_UI` variable to the lxd service e.g. via `systemctl edit lxd.service`:
```
[Service]
LXD_UI=/usr/share/lxd-ui/ui
```

**Comment by almereyda** [comment]
Many thanks for the effort, very well done.

Even though I had adapted the snippet to read

```diff
[Service]
< LXD_UI=/usr/share/lxd-ui/ui
> Environment=LXD_UI=/usr/share/lxd-ui/ui
```

LXD would not bind to the expected port :8443, until I had activated the API with `lxc config set core.https_address :8443`.

Then I was greeted with a way to set the token for the certificate that was offered, and could manage the service.

- The page https://localhost:8443/ui/project/default/storage/cached-images only shows blank until a reload, but that could come from upstream.

Should this issue remain open, until the package also builds for other platforms?

**Comment by ganto** [comment]
Ah, sorry about the wrong service snipped. 

Btw. thanks for all the links that you posted. They help me a lot. 

Now I'm still struggling with some Javascript build issues. I'd like to leave the issue open until I fixed that. Hopefully it will keep me motivated to fix it soon.

**Comment by almereyda** [comment]
Cool, go on. People will be surprised to hear that this even exists and just works™

**Comment by ganto** [comment]
The `lxd-ui` package is now available for all Fedora architectures. With `>=lxd-5.18-0.2` I also adjusted the `lxd` systemd service so that the path to the UI (and the documentation) must no longer be set manually. 

How to enable the UI is now also [explained in the wiki](https://github.com/ganto/copr-lxc4/wiki/Getting-Started-with-LXD-on-Fedora#enable-lxd-ui). I hope this should be good enough for everyone interested to figure out how to use it.

**Comment by almereyda** [comment]
You were faster than Incus, which is a little nice.

- https://github.com/zabbly/incus/issues/7

Since they only publish `.deb` packages, are you also considering to package them at some point?
