### ISSUE TITLE
incus fails to start on Silverblue

### ISSUE THREAD

**Issue by bketelsen** [ganto/copr-lxc4#37]
incus fails to start because of two missing directories:

/var/lib/incus
/var/log/incus

Similar to #36 I think this can be solved with an `ExecStartPre`

**Comment by ganto** [comment]
I'm not so familiar with Silverblue. Could you quickly tell me how to reproduce the issue?

As far as I remember one is not supposed to install packages into the OSTree layer as there is no persistence. I guess all your containers in /var/lib/incus are gone again after a reboot?

**Comment by bketelsen** [comment]
We’re installing incus in https://projectbluefin.io which is based on Silverblue, but the OS image is an OCI artifact. The images get created on GitHub and rpm-ostree installs them when we update.  Incus is installed during the image creation so the binaries live in the immutable /usr directories. Everything in /var persists between updates so there is no problem with losing data.To reproduce, spin up a Bluefin-DX (developer edition) VM and try to start incus. Or start with Silverblue and overlay Incus. The services will fail to start because the /var/lib and /var/log directories for incus and lxcfs don’t exist. Creating the directories manually and restarting the services solves the problem.On Dec 22, 2023, at 5:45 AM, Reto Gantenbein ***@***.***> wrote:﻿
I'm not so familiar with Silverblue. Could you quickly tell me how to reproduce the issue?
As far as I remember one is not supposed to install packages into the OSTree layer as there is no persistence. I guess all your containers in /var/lib/incus are gone again after a reboot?

**Comment by ganto** [comment]
Issue should be fixed by 63fb27e82d26020524c9d7b2953140df6ed82886 which is available via `incus-0.4-0.2`.

**Comment by bketelsen** [comment]
waiting for that to propagate and I'll test in a clean VM, thanks for the fix!

**Comment by ganto** [comment]
Ok, I'll close the issue. If there should be any more problem just reopen.
