### ISSUE TITLE
LXD 5.19 removed SELinux workarounds.

### ISSUE THREAD

**Issue by m2Giles** [ganto/copr-lxc4#41]
In 5.18 and before there was an lxd.profile that set the LXD_SOCKET to /run/lxd.socket and the lxd.socket has the same change. This and possibly other changes made lxd work with SELinux in enforcing mode and why I haven't switched over to incus yet.

Was this change intended? It brings things to parity with incus.

**Comment by ganto** [comment]
Sorry, I wasn't aware that this work-around was still working. As I was playing around with `lxd-user` (#21) I "fixed" the socket to be at the default path again.

I will test again and will put the work-around in place again by default if that's all what is needed.

Until then you can put the work-around in place yourself. All that you need to do is to create the following files and restart:
* `/etc/profile.d/lxd.sh`:
```shell
# /etc/profile.d/lxd.sh - Set LXD socket path

LXD_SOCKET=/run/lxd.socket
export LXD_SOCKET
```
* `/etc/systemd/system/lxd.socket.d/override.conf`:
```ini
[Socket]
ListenStream=
ListenStream=/run/lxd.socket
```
* `/etc/systemd/system/lxd.service.d/override.conf`:
```ini
[Service]
Environment=LXD_SOCKET=/run/lxd.socket
```
* `/etc/systemd/system/lxd-containers.service.d/override.conf`:
```ini
[Service]
Environment=LXD_SOCKET=/run/lxd.socket
```

**Comment by m2Giles** [comment]
Yepp, I've made those changes already and it was back to working.

**Comment by m2Giles** [comment]
Instead of going through all of those changes. The only changes necessary is having the socket unit create the socket in /run/.

Instead of changing profile to then point there, a symlink to the default socket location works and doesn't require setting the socket location.

This also works for incus.

**Comment by ganto** [comment]
`lxd-5.20` should now properly set the correct SELinux labels for the socket.
