### ISSUE TITLE
OVMF symlinks for secureboot

### ISSUE THREAD

**Issue by m2Giles** [ganto/copr-lxc4#42]
For Incus and LXD VMs, secureboot config key must be set to false.

We can instead create symlinks to match the expected name. Inside /usr/share/edk/ovmf. If on an immutable system you will need to do this in a different location, symlink the full path, and change the {INCUS,LXD}_OVMF_PATH in {incus,lxd}.service file.

```
ln -s OVMF_CODE.secboot.fd OVMF_CODE.ms.fd
ln -s OVMF_VARS.secboot.fd OVMF_VARS.ms.fd
```

This should be enough to no longer need the secuerboot config key.

**Comment by ganto** [comment]
Thanks for the hint. I'll give it a try.
