### ISSUE TITLE
incus-user.socket is not enabled at startup

### ISSUE THREAD

**Issue by keestux** [ganto/copr-lxc4#47]
The `incus-user.socket` is not enabled at starup.

BTW. See:
- https://discuss.linuxcontainers.org/t/how-to-setup-a-non-admin-incus-user-on-fedora-40
- https://linuxcontainers.org/incus/docs/main/packaging/

**Comment by ganto** [comment]
In the Red Hat/Fedora world services are usually not enabled by default after installing a package.

My [documentation](https://github.com/ganto/copr-lxc4/wiki/Getting-Started-with-Incus-on-Fedora#manage-less-privileged-incus-users) properly describes the necessary steps to be done for Incus non-admin users.

**Comment by keestux** [comment]
That's now how it is intended. Incus is meant to be enabled through `incus.socket` and `incus-user.socket`. It's a cheap systemd mechanism. The actual daemon will not be started unless someone runs the `incus` command.

**Comment by keestux** [comment]
BTW. I appreciate you writing up documentation, however the packaging recommendation explicitely says:

> Packaging recommendations

> Below are a few recommendations for packagers of Incus.

> Following those recommendations should provide a **more predictable experience across Linux distributions**.
...
> incus-user.socket is the socket-activation unit for the incus-user.service unit. If present, incus-user.service should not be made to start on its own.

Why make Fedora a less predicable Linux distribution for Incus? Did you read [the Stephane's remark](https://discuss.linuxcontainers.org/t/how-to-setup-a-non-admin-incus-user-on-fedora-40/20186/4)?

**Comment by ganto** [comment]
I'm aware how socket activation works in systemd. I guess the reason why services are not enabled by default is to keep the potential attack surface as small as possible if you have packages installed that contain services. 

> Why make Fedora a less predicable Linux distribution for Incus

What is predictable and not is in the eye of the user. An experienced Fedora user that is not aware Stephane's recommendations doesn't expect stuff to just be enabled by default.

For now I won't change anything in my community package but we might continue the discussion for the [official Incus Fedora package](https://packages.fedoraproject.org/pkgs/incus/). According to the [Fedora Packaging Guidelines related to socket activation](https://docs.fedoraproject.org/en-US/packaging-guidelines/Systemd/#activation_socket) it doesn't seem against the rules to have it enabled by default.

**Comment by keestux** [comment]
@ganto So, where can we continue the discussion for the official Fedora package?
