### ISSUE TITLE
Error in incus.service

### ISSUE THREAD

**Issue by LOTRg** [ganto/copr-lxc4#48]
Incus version 6.3

Previous version 6.2 installed incus daemon in `/usr/lib/incus` but his version install the executable in `/usr/libexec/incus`

File incus/incus.service, incus/incus-startup.service and incus/incus-user.service has incorrect path in the systemd service unit, which prevents the service from starting or finding incusd.
the correct path is **`/usr/libexec/incus`**

please update paths in the systemd service unit files or make a symlink to the specified path `**/usr/lib/incus/**` for both incusd and incus-user.

In addition, the SELinux Module for FContext will need to be adjusted for the new path from 
`/usr/lib/incus(/.*)?                all files        system_u:object_r:container_runtime_exec_t:s0 `
to
 `/usr/libexec/incus(/.*)?       all files       system_u:object_r:container_runtime_exec_t:s0 `
or gaining shell/exec commands will fail with error message 

> "Error: Command not executable"

Thank you

**Comment by ganto** [comment]
Ah... sorry for that.

Although I tested the new release I suddenly decided to adjust the spec file to the Fedora spec which had this minor adjustment. Thanks for reporting. Fix is on the way...

**Comment by LOTRg** [comment]
Thank you for your prompt response.

**Comment by ganto** [comment]
Issue is fixed with `incus-6.3-0.2`
