### ISSUE TITLE
Buggy upstream Incusd 

### ISSUE THREAD

**Issue by LOTRg** [ganto/copr-lxc4#49]
Incusd when ran causes the runtime directory /run/incus to have permissions of 0700, the issue was reported here https://github.com/lxc/incus/issues/1003 and here https://github.com/lxc/incus/issues/1010 a fix was commited here https://github.com/lxc/incus/commit/d69c680903eff251e987d90af729992d2e141f9c and awaiting a new update please to fix the RPM.

Thank you!

**Comment by ganto** [comment]
Thanks a lot for this report. I added the patch to `incus-6.3-0.3`.

But at the same time I reverted the socket path back to `/var/lib/incus`. The Fedora package switched to `/run/incus` and I blindly copied it without being aware of the issues. Actually I prefer to not break stuff for no reason.

Hope this was the last fallout of this spec file synchronization attempt.
