### ISSUE TITLE
LXD UI not available on Fedora 40

### ISSUE THREAD

**Issue by biladina** [ganto/copr-lxc4#50]
I tried to install `lxd-ui` package on Fedora 40, but the package not found..

this is the message from `dnf`:

```
Last metadata expiration check: 0:01:43 ago on Fri 25 Oct 2024 11:47:50 AM WIB.
No match for argument: lxd-ui
Error: Unable to find a match: lxd-ui
```

and I look into the `lxd-ui` build, there is no package build for Fedora 40,
[https://copr.fedorainfracloud.org/coprs/ganto/lxc4/build/6716608/](https://copr.fedorainfracloud.org/coprs/ganto/lxc4/build/6716608/)

**Comment by ganto** [comment]
Ok, I updated lxd-ui once again so that it's also available on Fedora 40 now. 

But note that I won't maintain the lxd-related packages much longer. Please migrate to Incus if possible.
